engineering:
  members:
    - bistacos
    - derekgeeting
    - jlgoolsbee
    - JF90

  channel:
    "#engineering"

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Pick up work from the 'ready column' - don't cherry pick from the backlog/ice box or ‘next’ column.
    - Any excuse for cake - or generally celebrating awesomeness!
    - Never be afraid to suggest better ways of working.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge.
    - Ask if anyone needs support before picking up new work.
    - Be considerate to remote workers.
    - Stories should start with a user need.
    - It’s not done until it’s in the hands of the people who need it.
    - When working at home, dial in to stand-up.
    - Communicate what you’re working on - make sure you don’t leave people out of the loop.
